### ISSUE TITLE
pub get failed

### ISSUE THREAD

**Issue by vutmini** [princesanjivy/do-touch#1]
Tried to use this plugin but got 'pub get failed' when added do-touch in pubspec dependencies.

**Comment by princesanjivy** [comment]
This package is not published or packaged. To use this package import using the path in your `pubspec.yaml` 
```yaml
dependencies:
    do_touch:
        path: # add the path to do_touch
```
